# Generated by Django 6.0.4 on 2026-04-27 17:36

import demo_ingest.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demo_ingest", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demoanalysisjob",
            name="demo_file",
            field=models.FileField(upload_to=demo_ingest.models.demo_upload_to),
        ),
    ]
